version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/trx-test
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
